# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
 push:
    branches: [ main ]
 pull_request:
    branches: [ main ]

jobs:
  install-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url:  https://registry.npmjs.org/
      - name: install
        run: |
         yarn config set registry https://registry.npm.taobao.org/
         yarn install
      - name: build
        run: |
          yarn build-storybook
          yarn build
      - name: publish-gpr
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      - name: publish-pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: storybook-static
          token: ${{ secrets.PERSONAL_TOKEN }}
          clean: true
          branch: gh-pages
